<?php

namespace App\Repository;


use App\Entity\charge;
use App\Entity\messages;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * conversationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class chargeRepository extends ServiceEntityRepository
{
	public function __construct(RegistryInterface $registry)
	{
		parent::__construct($registry, charge::class);
	}

	/**
	 * @param $id
	 * @return charge[]
	 */
	public function selectCharge($id): array
	{
		$qb = $this->createQueryBuilder('c')
			->InnerJoin('c.proprio', 'p')
			->andWhere('p = :user')
			->setParameter('user', $id)
			->getQuery();
		return $qb->execute();
	}

	/**
	 * @param $id
	 * @return charge[]
	 */
	public function authorisation($id, $charge): array
	{
		$qb = $this->createQueryBuilder('c')
			->InnerJoin('c.proprio', 'p')
			->addSelect('p')
			->andWhere('c.id = :charge')
			->andWhere('p = :user')
			->setParameter('user', $id)
			->setParameter('conv', $charge)
			->getQuery();
		return $qb->execute();
	}
}