<?php

namespace App\Repository;

use App\Entity\fil_messages;
use App\Entity\messages;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
* conversationRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class conversationRepository extends ServiceEntityRepository
{
	public function __construct(RegistryInterface $registry)
	{
		parent::__construct($registry, fil_messages::class);
	}

	/**
	 * @param $id
	 * @return fil_messages[]
	 */
	public function selectConversation($id): array
	{
		$qb = $this->createQueryBuilder('f')
		->InnerJoin('f.destinataire', 'd')
		->addSelect('d')
		->andWhere('d = :user')
		->setParameter('user', $id)
		->getQuery();
		return $qb->execute();
	}

	/**
	 * @param $id
	 * @return fil_messages[]
	 */
	public function authorisation($id, $conversation): array
	{
		$qb = $this->createQueryBuilder('f')
			->InnerJoin('f.destinataire', 'd')
			->addSelect('d')
			->andWhere('f.id = :conv')
			->andWhere('d = :user')
			->setParameter('user', $id)
			->setParameter('conv', $conversation)
			->getQuery();
		return $qb->execute();
	}
}